## DSC 640 Term Project
* Milestone 1
* Mallory Young

## Exploring the Data
* Importing code and packages needed for this project
* Importing and displaying the data frame
* Filtering the data to only include Florida Data
* Checking for missing values
* Filtering the data to only include the columns relevant to my story

In [1]:
import pandas as pd

In [2]:
#load the Excel file into a DataFrame
df = pd.read_excel('nationaldatabaseofchildcareprices.xlsx')

#display the DataFrame
df.head()

,State_Name,State_Abbreviation,County_Name,County_FIPS_Code,StudyYear,UNR_16,FUNR_16,MUNR_16,UNR_20to64,FUNR_20to64,...,MFCCToddler,MFCCToddler_flag,MFCCPreschool,MFCCPreschool_flag,_75FCCInfant,_75FCCInfant_flag,_75FCCToddler,_75FCCToddler_flag,_75FCCPreschool,_75FCCPreschool_flag
0,Alabama,AL,Autauga County,1001,2008,5.42,4.41,6.32,4.6,3.5,...,83.45,3.0,81.40,1.0,97.4,1.0,97.4,3.0,95.0,1.0
1,Alabama,AL,Autauga County,1001,2009,5.93,5.72,6.11,4.8,4.6,...,87.39,3.0,85.68,1.0,102.0,1.0,102.0,3.0,100.0,1.0
2,Alabama,AL,Autauga County,1001,2010,6.21,5.57,6.78,5.1,4.6,...,91.33,3.0,89.96,1.0,106.6,1.0,106.6,3.0,105.0,1.0
3,Alabama,AL,Autauga County,1001,2011,7.55,8.13,7.03,6.2,6.3,...,95.28,3.0,94.25,1.0,111.2,1.0,111.2,3.0,110.0,1.0
4,Alabama,AL,Autauga County,1001,2012,8.60,8.88,8.29,6.7,6.4,...,99.22,3.0,98.53,1.0,115.8,1.0,115.8,3.0,115.0,1.0

In [3]:
df.shape

(34567, 227)

In [4]:
#filter the DataFrame to keep only rows where State_Name is Florida
florida_df = df[df['State_Name'] == 'Florida']

#display the filtered DataFrame
florida_df.head(50)

,State_Name,State_Abbreviation,County_Name,County_FIPS_Code,StudyYear,UNR_16,FUNR_16,MUNR_16,UNR_20to64,FUNR_20to64,...,MFCCToddler,MFCCToddler_flag,MFCCPreschool,MFCCPreschool_flag,_75FCCInfant,_75FCCInfant_flag,_75FCCToddler,_75FCCToddler_flag,_75FCCPreschool,_75FCCPreschool_flag
3519,Florida,FL,Alachua County,12001,2008,5.18,5.50,4.88,4.10,4.70,...,104.96,1.0,102.82,3.0,125.00,1.0,122.50,1.0,120.00,3.0
3520,Florida,FL,Alachua County,12001,2009,6.75,6.45,7.03,5.80,5.60,...,107.10,1.0,102.82,3.0,125.00,1.0,125.00,1.0,120.00,3.0
3521,Florida,FL,Alachua County,12001,2010,6.69,6.75,6.64,5.80,6.10,...,111.57,1.0,102.94,3.0,131.25,1.0,130.47,1.0,122.19,3.0
3522,Florida,FL,Alachua County,12001,2011,7.33,7.25,7.41,6.70,6.80,...,116.05,1.0,103.07,3.0,137.50,1.0,135.94,1.0,124.38,3.0
3523,Florida,FL,Alachua County,12001,2012,7.87,7.36,8.36,7.30,6.90,...,120.52,1.0,103.20,3.0,143.75,1.0,141.41,1.0,126.56,3.0
3524,Florida,FL,Alachua County,12001,2013,8.64,7.91,9.37,8.10,7.50,...,125.00,1.0,103.33,1.0,150.00,1.0,146.88,1.0,128.75,1.0
3525,Florida,FL,Alachua County,12001,2014,8.50,7.94,9.14,8.10,7.70,...,125.00,1.0,109.17,1.0,158.75,1.0,147.82,1.0,129.17,1.0
3526,Florida,FL,Alachua County,12001,2015,7.86,7.30,8.42,7.40,6.80,...,125.00,1.0,115.00,1.0,167.50,1.0,148.75,1.0,129.58,1.0
3527,Florida,FL,Alachua County,12001,2016,7.02,6.33,7.71,6.50,5.70,...,125.00,1.0,120.84,1.0,176.25,1.0,149.69,1.0,130.00,1.0
3528,Florida,FL,Alachua County,12001,2017,6.65,6.17,7.13,6.20,5.60,...,125.00,1.0,126.67,1.0,185.00,1.0,150.62,1.0,142.73,1.0
3529,Florida,FL,Alachua County,12001,2018,6.11,5.46,6.74,5.70,4.90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3530,Florida,FL,Baker County,12003,2008,6.89,5.07,8.44,6.17,3.43,...,92.11,1.0,83.54,3.0,112.50,3.0,107.50,1.0,97.50,3.0
3531,Florida,FL,Baker County,12003,2009,8.00,5.82,9.88,7.30,4.00,...,102.82,1.0,85.68,3.0,125.00,3.0,120.00,1.0,100.00,3.0
3532,Florida,FL,Baker County,12003,2010,7.26,6.02,8.36,6.20,4.10,...,100.21,1.0,86.34,3.0,118.75,3.0,114.38,1.0,97.50,3.0
3533,Florida,FL,Baker County,12003,2011,10.97,8.95,12.73,10.10,6.50,...,97.61,1.0,87.00,3.0,112.50,3.0,108.75,1.0,95.00,3.0
3534,Florida,FL,Baker County,12003,2012,10.53,7.80,12.88,9.70,6.30,...,95.00,1.0,87.67,3.0,106.25,3.0,103.13,1.0,92.50,3.0
3535,Florida,FL,Baker County,12003,2013,11.39,7.76,14.55,10.10,6.70,...,92.40,1.0,88.33,1.0,100.00,1.0,97.50,1.0,90.00,1.0
3536,Florida,FL,Baker County,12003,2014,9.80,7.65,11.73,9.10,7.40,...,91.20,1.0,83.75,1.0,110.00,1.0,99.07,1.0,89.17,1.0
3537,Florida,FL,Baker County,12003,2015,8.92,6.63,10.93,8.10,6.30,...,90.00,1.0,79.17,1.0,120.00,1.0,100.63,1.0,88.33,1.0
3538,Florida,FL,Baker County,12003,2016,6.83,4.74,8.82,6.60,5.10,...,88.80,1.0,74.59,1.0,130.00,1.0,102.20,1.0,87.50,1.0
3539,Florida,FL,Baker County,12003,2017,5.84,3.92,7.67,5.80,4.20,...,87.60,1.0,70.01,1.0,140.00,1.0,103.76,1.0,86.66,1.0
3540,Florida,FL,Baker County,12003,2018,5.51,4.54,6.46,5.50,4.80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3541,Florida,FL,Bay County,12005,2008,5.58,6.25,4.94,4.90,5.70,...,116.33,1.0,112.02,3.0,150.00,3.0,135.00,1.0,130.00,3.0
3542,Florida,FL,Bay County,12005,2009,6.44,6.78,6.11,5.70,6.30,...,124.95,1.0,116.33,3.0,150.00,1.0,145.00,1.0,135.00,3.0
3543,Florida,FL,Bay County,12005,2010,7.46,7.22,7.69,6.80,6.80,...,122.46,1.0,112.25,3.0,147.19,1.0,140.00,1.0,127.50,3.0
3544,Florida,FL,Bay County,12005,2011,8.18,7.39,8.90,7.50,7.00,...,119.97,1.0,108.16,3.0,144.38,1.0,135.00,1.0,120.00,3.0
3545,Florida,FL,Bay County,12005,2012,9.46,8.63,10.23,8.80,8.20,...,117.49,1.0,104.08,3.0,141.56,1.0,130.00,1.0,112.50,3.0
3546,Florida,FL,Bay County,12005,2013,9.87,8.81,10.86,9.30,8.40,...,115.00,1.0,100.00,1.0,138.75,1.0,125.00,1.0,105.00,1.0
3547,Florida,FL,Bay County,12005,2014,9.80,8.58,10.99,9.30,8.00,...,110.63,1.0,100.00,1.0,140.00,1.0,125.94,1.0,108.34,1.0
3548,Florida,FL,Bay County,12005,2015,8.63,7.61,9.57,8.00,7.20,...,106.25,1.0,100.00,1.0,141.25,1.0,126.88,1.0,111.67,1.0
3549,Florida,FL,Bay County,12005,2016,7.48,6.73,8.15,6.90,6.40,...,101.88,1.0,100.00,1.0,142.50,1.0,127.82,1.0,115.01,1.0
3550,Florida,FL,Bay County,12005,2017,6.39,5.50,7.20,6.10,5.30,...,97.50,1.0,100.00,1.0,143.75,1.0,128.76,1.0,118.34,1.0
3551,Florida,FL,Bay County,12005,2018,6.04,5.57,6.47,5.80,5.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3552,Florida,FL,Bradford County,12007,2008,4.76,6.48,3.68,4.30,5.70,...,109.87,1.0,92.63,3.0,127.50,1.0,127.50,1.0,107.50,3.0
3553,Florida,FL,Bradford County,12007,2009,7.99,10.07,6.33,8.10,10.20,...,107.71,1.0,99.09,3.0,130.00,3.0,125.00,1.0,115.00,3.0
3554,Florida,FL,Bradford County,12007,2010,9.97,10.03,9.91,9.70,9.90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3555,Florida,FL,Bradford County,12007,2011,13.20,12.84,13.51,13.00,12.80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3556,Florida,FL,Bradford County,12007,2012,15.06,13.32,16.49,14.60,13.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3557,Florida,FL,Bradford County,12007,2013,15.68,14.26,16.94,15.10,14.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3558,Florida,FL,Bradford County,12007,2014,14.50,13.59,15.33,14.40,13.40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3559,Florida,FL,Bradford County,12007,2015,12.38,12.29,12.47,12.10,12.00,...,107.50,1.0,96.67,1.0,125.00,1.0,115.00,1.0,115.00,1.0
3560,Florida,FL,Bradford County,12007,2016,10.56,10.19,10.91,10.40,9.90,...,107.46,1.0,99.86,3.0,127.88,3.0,114.96,1.0,119.17,3.0
3561,Florida,FL,Bradford County,12007,2017,7.55,9.03,6.11,7.20,8.70,...,107.43,1.0,103.04,3.0,130.76,3.0,114.92,1.0,123.33,3.0
3562,Florida,FL,Bradford County,12007,2018,5.91,7.13,4.80,5.40,6.70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3563,Florida,FL,Brevard County,12009,2008,6.30,6.10,6.46,5.50,5.50,...,103.40,1.0,101.25,3.0,132.50,3.0,120.00,1.0,117.50,3.0
3564,Florida,FL,Brevard County,12009,2009,7.13,7.27,7.00,6.40,6.60,...,107.71,1.0,107.71,3.0,140.00,3.0,125.00,1.0,125.00,3.0
3565,Florida,FL,Brevard County,12009,2010,8.79,8.89,8.71,8.00,8.20,...,112.03,1.0,108.28,3.0,140.63,3.0,126.25,1.0,125.00,3.0
3566,Florida,FL,Brevard County,12009,2011,10.58,10.54,10.61,9.90,9.90,...,116.36,1.0,108.86,3.0,141.25,3.0,127.50,1.0,125.00,3.0
3567,Florida,FL,Brevard County,12009,2012,11.80,11.56,12.01,11.00,10.90,...,120.68,1.0,109.43,3.0,141.88,3.0,128.75,1.0,125.00,3.0
3568,Florida,FL,Brevard County,12009,2013,12.38,11.93,12.78,11.60,11.30,...,125.00,1.0,110.00,1.0,142.50,1.0,130.00,1.0,125.00,1.0

In [5]:
florida_df.shape

(737, 227)

In [6]:
#show all columns
pd.set_option('display.max_columns', None) 
#show all rows
pd.set_option('display.max_rows', None) 
#prevent wrapping
pd.set_option('display.expand_frame_repr', False)  
#creating a list of the column names
florida_df.columns.tolist()  
#I will use this list of column names to filter only the columns I want to keep

['State_Name',
 'State_Abbreviation',
 'County_Name',
 'County_FIPS_Code',
 'StudyYear',
 'UNR_16',
 'FUNR_16',
 'MUNR_16',
 'UNR_20to64',
 'FUNR_20to64',
 'MUNR_20to64',
 'FLFPR_20to64',
 'FLFPR_20to64_Under6',
 'FLFPR_20to64_6to17',
 'FLFPR_20to64_Under6_6to17',
 'MLFPR_20to64',
 'PR_F',
 'PR_P',
 'MHI',
 'ME',
 'FME',
 'MME',
 'MHI_2018',
 'ME_2018',
 'FME_2018',
 'MME_2018',
 'TotalPop',
 'OneRace',
 'OneRace_W',
 'OneRace_B',
 'OneRace_I',
 'OneRace_A',
 'OneRace_H',
 'OneRace_Other',
 'TwoRaces',
 'Hispanic',
 'Households',
 'H_Under6_BothWork',
 'H_Under6_FWork',
 'H_Under6_MWork',
 'H_Under6_SingleM',
 'H_6to17_BothWork',
 'H_6to17_Fwork',
 'H_6to17_Mwork',
 'H_6to17_SingleM',
 'EMP_M',
 'MEMP_M',
 'FEMP_M',
 'EMP_Service',
 'MEMP_Service',
 'FEMP_Service',
 'EMP_Sales',
 'MEMP_Sales',
 'FEMP_Sales',
 'EMP_N',
 'MEMP_N',
 'FEMP_N',
 'EMP_P',
 'MEMP_P',
 'FEMP_P',
 'iUNR_16',
 'iFUNR_16',
 'iMUNR_16',
 'iUNR_20to64',
 'iFUNR_20to64',
 'iMUNR_20to64',
 'iFLFPR_20to64',
 'iFLFPR_20to64_Under6',
 'iFLFPR_20to64_6to17',
 'iFLFPR_20to64_Under6_6to17',
 'iMLFPR_20to64',
 'iPR_F',
 'iPR_P',
 'iMHI',
 'iME',
 'iFME',
 'iMME',
 'iMHI_2018',
 'iME_2018',
 'iFME_2018',
 'iMME_2018',
 'iTotalPop',
 'iOneRace',
 'iOneRace_W',
 'iOneRace_B',
 'iOneRace_I',
 'iOneRace_A',
 'iOneRace_H',
 'iOneRace_Other',
 'iTwoRaces',
 'iHispanic',
 'iHouseholds',
 'iH_Under6_BothWork',
 'iH_Under6_FWork',
 'iH_Under6_MWork',
 'iH_Under6_SingleM',
 'iH_6to17_BothWork',
 'iH_6to17_Fwork',
 'iH_6to17_Mwork',
 'iH_6to17_SingleM',
 'iEMP_M',
 'iMEMP_M',
 'iFEMP_M',
 'iEMP_Service',
 'iMEMP_Service',
 'iFEMP_Service',
 'iEMP_Sales',
 'iMEMP_Sales',
 'iFEMP_Sales',
 'iEMP_N',
 'iMEMP_N',
 'iFEMP_N',
 'iEMP_P',
 'iMEMP_P',
 'iFEMP_P',
 'MCBto5',
 'MC6to11',
 'MC12to17',
 'MC18to23',
 'MC24to29',
 'MC30to35',
 'MC36to41',
 'MC42to47',
 'MC48to53',
 'MC54toSA',
 'MCSA',
 'MFCCBto5',
 'MFCC6to11',
 'MFCC12to17',
 'MFCC18to23',
 'MFCC24to29',
 'MFCC30to35',
 'MFCC36to41',
 'MFCC42to47',
 'MFCC48to53',
 'MFCC54toSA',
 'MFCCSA',
 '_75CBto5',
 '_75C6to11',
 '_75C12to17',
 '_75C18to23',
 '_75C24to29',
 '_75C30to35',
 '_75C36to41',
 '_75C42to47',
 '_75C48to53',
 '_75C54toSA',
 '_75CSA',
 '_75FCCBto5',
 '_75FCC6to11',
 '_75FCC12to17',
 '_75FCC18to23',
 '_75FCC24to29',
 '_75FCC30to35',
 '_75FCC36to41',
 '_75FCC42to47',
 '_75FCC48to53',
 '_75FCC54toSA',
 '_75FCCSA',
 'iMCBto5',
 'iMC6to11',
 'iMC12to17',
 'iMC18to23',
 'iMC24to29',
 'iMC30to35',
 'iMC36to41',
 'iMC42to47',
 'iMC48to53',
 'iMC54toSA',
 'iMCSA',
 'iMFCCBto5',
 'iMFCC6to11',
 'iMFCC12to17',
 'iMFCC18to23',
 'iMFCC24to29',
 'iMFCC30to35',
 'iMFCC36to41',
 'iMFCC42to47',
 'iMFCC48to53',
 'iMFCC54toSA',
 'iMFCCSA',
 'i_75CBto5',
 'i_75C6to11',
 'i_75C12to17',
 'i_75C18to23',
 'i_75C24to29',
 'i_75C30to35',
 'i_75C36to41',
 'i_75C42to47',
 'i_75C48to53',
 'i_75C54toSA',
 'i_75CSA',
 'i_75FCCBto5',
 'i_75FCC6to11',
 'i_75FCC12to17',
 'i_75FCC18to23',
 'i_75FCC24to29',
 'i_75FCC30to35',
 'i_75FCC36to41',
 'i_75FCC42to47',
 'i_75FCC48to53',
 'i_75FCC54toSA',
 'i_75FCCSA',
 'MCInfant',
 'MCInfant_flag',
 'MCToddler',
 'MCToddler_flag',
 'MCPreschool',
 'MCPreschool_flag',
 '_75CInfant',
 '_75CInfant_flag',
 '_75CToddler',
 '_75CToddler_flag',
 '_75CPreschool',
 '_75CPreschool_flag',
 'MFCCInfant',
 'MFCCInfant_flag',
 'MFCCToddler',
 'MFCCToddler_flag',
 'MFCCPreschool',
 'MFCCPreschool_flag',
 '_75FCCInfant',
 '_75FCCInfant_flag',
 '_75FCCToddler',
 '_75FCCToddler_flag',
 '_75FCCPreschool',
 '_75FCCPreschool_flag']

In [7]:
#finding the count of NaN values in each column
nan_counts = florida_df.isna().sum()

#Display the counts of NaN values for each column
print(nan_counts)

State_Name                      0
State_Abbreviation              0
County_Name                     0
County_FIPS_Code                0
StudyYear                       0
UNR_16                          0
FUNR_16                         0
MUNR_16                         0
UNR_20to64                      0
FUNR_20to64                     0
MUNR_20to64                     0
FLFPR_20to64                    0
FLFPR_20to64_Under6             0
FLFPR_20to64_6to17              0
FLFPR_20to64_Under6_6to17       0
MLFPR_20to64                    0
PR_F                            0
PR_P                            0
MHI                             0
ME                              0
FME                             0
MME                             0
MHI_2018                        0
ME_2018                         0
FME_2018                        0
MME_2018                        0
TotalPop                        0
OneRace                         0
OneRace_W                       0
OneRace_B                       0
OneRace_I                       0
OneRace_A                       0
OneRace_H                       0
OneRace_Other                   0
TwoRaces                        0
Hispanic                        0
Households                      0
H_Under6_BothWork               0
H_Under6_FWork                  0
H_Under6_MWork                  0
H_Under6_SingleM                0
H_6to17_BothWork                0
H_6to17_Fwork                   0
H_6to17_Mwork                   0
H_6to17_SingleM                 0
EMP_M                           0
MEMP_M                          0
FEMP_M                          0
EMP_Service                     0
MEMP_Service                    0
FEMP_Service                    0
EMP_Sales                       0
MEMP_Sales                      0
FEMP_Sales                      0
EMP_N                           0
MEMP_N                          0
FEMP_N                          0
EMP_P                           0
MEMP_P                          0
FEMP_P                          0
iUNR_16                         0
iFUNR_16                        0
iMUNR_16                        0
iUNR_20to64                     0
iFUNR_20to64                    0
iMUNR_20to64                    0
iFLFPR_20to64                   0
iFLFPR_20to64_Under6            0
iFLFPR_20to64_6to17             0
iFLFPR_20to64_Under6_6to17      0
iMLFPR_20to64                   0
iPR_F                           0
iPR_P                           0
iMHI                            0
iME                             0
iFME                            0
iMME                            0
iMHI_2018                       0
iME_2018                        0
iFME_2018                       0
iMME_2018                       0
iTotalPop                       0
iOneRace                        0
iOneRace_W                      0
iOneRace_B                      0
iOneRace_I                      0
iOneRace_A                      0
iOneRace_H                      0
iOneRace_Other                  0
iTwoRaces                       0
iHispanic                       0
iHouseholds                     0
iH_Under6_BothWork              0
iH_Under6_FWork                 0
iH_Under6_MWork                 0
iH_Under6_SingleM               0
iH_6to17_BothWork               0
iH_6to17_Fwork                  0
iH_6to17_Mwork                  0
iH_6to17_SingleM                0
iEMP_M                          0
iMEMP_M                         0
iFEMP_M                         0
iEMP_Service                    0
iMEMP_Service                   0
iFEMP_Service                   0
iEMP_Sales                      0
iMEMP_Sales                     0
iFEMP_Sales                     0
iEMP_N                          0
iMEMP_N                         0
iFEMP_N                         0
iEMP_P                          0
iMEMP_P                         0
iFEMP_P                         0
MCBto5                         76
MC6to11                        76
MC12to17                       76
MC18to23                       76
MC24to29                       76
MC30to35                       76
MC36to41                       76
MC42to47                       76
MC48to53                       76
MC54toSA                       76
MCSA                           76
MFCCBto5                      105
MFCC6to11                     105
MFCC12to17                    105
MFCC18to23                    105
MFCC24to29                    105
MFCC30to35                    105
MFCC36to41                    105
MFCC42to47                    105
MFCC48to53                    105
MFCC54toSA                    105
MFCCSA                        105
_75CBto5                       76
_75C6to11                      76
_75C12to17                     76
_75C18to23                     76
_75C24to29                     76
_75C30to35                     76
_75C36to41                     76
_75C42to47                     76
_75C48to53                     76
_75C54toSA                     76
_75CSA                         76
_75FCCBto5                    105
_75FCC6to11                   105
_75FCC12to17                  105
_75FCC18to23                  105
_75FCC24to29                  105
_75FCC30to35                  105
_75FCC36to41                  105
_75FCC42to47                  105
_75FCC48to53                  105
_75FCC54toSA                  105
_75FCCSA                      105
iMCBto5                        76
iMC6to11                       76
iMC12to17                      76
iMC18to23                      76
iMC24to29                      76
iMC30to35                      76
iMC36to41                      76
iMC42to47                      76
iMC48to53                      76
iMC54toSA                      76
iMCSA                          76
iMFCCBto5                     105
iMFCC6to11                    105
iMFCC12to17                   105
iMFCC18to23                   105
iMFCC24to29                   105
iMFCC30to35                   105
iMFCC36to41                   105
iMFCC42to47                   105
iMFCC48to53                   105
iMFCC54toSA                   105
iMFCCSA                       105
i_75CBto5                      76
i_75C6to11                     76
i_75C12to17                    76
i_75C18to23                    76
i_75C24to29                    76
i_75C30to35                    76
i_75C36to41                    76
i_75C42to47                    76
i_75C48to53                    76
i_75C54toSA                    76
i_75CSA                        76
i_75FCCBto5                   105
i_75FCC6to11                  105
i_75FCC12to17                 105
i_75FCC18to23                 105
i_75FCC24to29                 105
i_75FCC30to35                 105
i_75FCC36to41                 105
i_75FCC42to47                 105
i_75FCC48to53                 105
i_75FCC54toSA                 105
i_75FCCSA                     105
MCInfant                       76
MCInfant_flag                  76
MCToddler                      76
MCToddler_flag                 76
MCPreschool                    76
MCPreschool_flag               76
_75CInfant                     76
_75CInfant_flag                76
_75CToddler                    76
_75CToddler_flag               76
_75CPreschool                  76
_75CPreschool_flag             76
MFCCInfant                    105
MFCCInfant_flag               105
MFCCToddler                   105
MFCCToddler_flag              105
MFCCPreschool                 105
MFCCPreschool_flag            105
_75FCCInfant                  105
_75FCCInfant_flag             105
_75FCCToddler                 105
_75FCCToddler_flag            105
_75FCCPreschool               105
_75FCCPreschool_flag          105
dtype: int64

In [8]:
#list of columns to keep (relevant to my story)
columns_to_keep = ['State_Name', 'County_Name', 'County_FIPS_Code', 'StudyYear', 'UNR_20to64', 'FUNR_20to64', 'MUNR_20to64', 'FLFPR_20to64_Under6',
                   'TotalPop', 'Households', 'H_Under6_BothWork', 'H_Under6_FWork', 'H_Under6_MWork', 'H_Under6_SingleM', 'MCInfant', 'MCInfant_flag', 
                   'MCToddler', 'MCToddler_flag', 'MCPreschool', 'MCPreschool_flag', '_75CInfant', '_75CInfant_flag', '_75CToddler', 
                   '_75CToddler_flag', '_75CPreschool', '_75CPreschool_flag']

#filter the DataFrame 
florida_df = florida_df[columns_to_keep]

In [9]:
#printing the first 20 rows of the dataframe
florida_df.head(20)

     State_Name     County_Name  County_FIPS_Code  StudyYear  UNR_20to64  FUNR_20to64  MUNR_20to64  FLFPR_20to64_Under6  TotalPop  Households  H_Under6_BothWork  H_Under6_FWork  H_Under6_MWork  H_Under6_SingleM  MCInfant  MCInfant_flag  MCToddler  MCToddler_flag  MCPreschool  MCPreschool_flag  _75CInfant  _75CInfant_flag  _75CToddler  _75CToddler_flag  _75CPreschool  _75CPreschool_flag
3519    Florida  Alachua County             12001       2008        4.10         4.70         3.60                67.10    239046       96894               5618            3675             498            4499.0    137.65            3.0     115.54             1.0       106.36               3.0      165.00              3.0       138.50               1.0         127.50                 3.0
3520    Florida  Alachua County             12001       2009        5.80         5.60         6.00                67.70    238990       96518               5236            4026             398            4258.0    145.99            3.0     126.80             1.0       116.79               3.0      175.00              3.0       152.00               1.0         140.00                 3.0
3521    Florida  Alachua County             12001       2010        5.80         6.10         5.60                67.30    244247       97540               5128            3696             431            4298.0    149.55            3.0     129.75             1.0       119.46               3.0      179.81              3.0       154.83               1.0         142.96                 3.0
3522    Florida  Alachua County             12001       2011        6.70         6.80         6.60                70.70    246203       97542               5467            3364             414            4376.0    153.10            3.0     132.69             1.0       122.12               3.0      184.61              3.0       157.67               1.0         145.93                 3.0
3523    Florida  Alachua County             12001       2012        7.30         6.90         7.60                70.00    247973       96544               5758            3416             392            4426.0    156.66            3.0     135.64             1.0       124.79               3.0      189.42              3.0       160.50               1.0         148.89                 3.0
3524    Florida  Alachua County             12001       2013        8.10         7.50         8.60                68.60    249848       96043               5496            3799             372            4632.0    160.22            1.0     138.58             1.0       127.45               1.0      194.22              1.0       163.33               1.0         151.85                 1.0
3525    Florida  Alachua County             12001       2014        8.10         7.70         8.60                69.70    251759       96137               5808            3705             365            4969.0    159.70            1.0     139.78             1.0       124.58               1.0      201.95              1.0       169.67               1.0         156.19                 1.0
3526    Florida  Alachua County             12001       2015        7.40         6.80         8.00                74.00    254218       96703               6176            3656             503            4568.0    159.18            1.0     140.97             1.0       121.71               1.0      209.68              1.0       176.01               1.0         160.53                 1.0
3527    Florida  Alachua County             12001       2016        6.50         5.70         7.30                74.00    256581       96336               6155            3718             555            4423.0    158.66            1.0     142.17             1.0       118.84               1.0      217.41              1.0       182.35               1.0         164.87                 1.0
3528    Florida  Alachua County             12001       2017        6.20         5.60         6.70                70.20    259865       97485               6417            3802             531            4285.0    158.14            1.0     143.36             1.0       115.97               1.0      225.14              1.0       188.69               1.0         169.21                 1.0
3529    Florida  Alachua County             12001       2018        5.70         4.90         6.50                69.10    263148       97048               7023            3659             462            4078.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3530    Florida    Baker County             12003       2008        6.17         3.43         8.44                71.98     25628        7672                823             277             128             658.0     93.85            3.0      89.68             1.0        83.42               3.0      112.50              3.0       107.50               1.0         100.00                 3.0
3531    Florida    Baker County             12003       2009        7.30         4.00        10.10                70.40     25478        7680                591             443             124             724.0    104.28            3.0      87.59             1.0        79.25               3.0      125.00              3.0       105.00               1.0          95.00                 3.0
3532    Florida    Baker County             12003       2010        6.20         4.10         8.20                74.70     26548        8309                719             393             129             811.0    109.51            3.0      92.57             1.0        83.40               3.0      126.51              3.0       106.88               1.0          95.73                 3.0
3533    Florida    Baker County             12003       2011       10.10         6.50        13.30                68.10     26863        8333                846             506              19             720.0    114.74            3.0      97.55             1.0        87.54               3.0      128.01              3.0       108.75               1.0          96.46                 3.0
3534    Florida    Baker County             12003       2012        9.70         6.30        12.60                67.50     27010        8424                851             550              14             707.0    119.97            3.0     102.52             1.0        91.69               3.0      129.52              3.0       110.63               1.0          97.19                 3.0
3535    Florida    Baker County             12003       2013       10.10         6.70        13.20                62.60     27069        8216                883             552              17             674.0    125.21            1.0     107.50             1.0        95.83               1.0      131.03              1.0       112.50               1.0          97.92                 1.0
3536    Florida    Baker County             12003       2014        9.10         7.40        10.70                67.20     27057        8351                883             432               6             684.0    127.60            1.0     111.25             1.0        97.92               1.0      133.01              1.0       115.00               1.0          98.96                 1.0
3537    Florida    Baker County             12003       2015        8.10         6.30         9.60                65.80     27135        8205                851             469               1             532.0    130.00            1.0     115.00             1.0       100.00               1.0      135.00              1.0       117.50               1.0         100.00                 1.0
3538    Florida    Baker County             12003       2016        6.60         5.10         8.10                73.70     27312        8270                994             376               2             547.0    132.40            1.0     118.75             1.0       102.09               1.0      136.99              1.0       120.00               1.0         102.09                 1.0

In [10]:
#finding the count of NaN values in each column
nan_counts2 = florida_df.isna().sum()

#Display the counts of NaN values for each column
print(nan_counts2)

State_Name              0
County_Name             0
County_FIPS_Code        0
StudyYear               0
UNR_20to64              0
FUNR_20to64             0
MUNR_20to64             0
FLFPR_20to64_Under6     0
TotalPop                0
Households              0
H_Under6_BothWork       0
H_Under6_FWork          0
H_Under6_MWork          0
H_Under6_SingleM        0
MCInfant               76
MCInfant_flag          76
MCToddler              76
MCToddler_flag         76
MCPreschool            76
MCPreschool_flag       76
_75CInfant             76
_75CInfant_flag        76
_75CToddler            76
_75CToddler_flag       76
_75CPreschool          76
_75CPreschool_flag     76
dtype: int64

### Observation: 
There are 76 rows out of 737 that contain all NaN values for all 12 of the last columns. These columns describe the childcare prices for each age group. This data is important to the story and these rows should evaluated on whether they should be dropped...

In [11]:
# Filter the DataFrame to show all rows with NaN values
rows_with_nan = florida_df[florida_df.isna().any(axis=1)]

# Display the filtered DataFrame
rows_with_nan

     State_Name          County_Name  County_FIPS_Code  StudyYear  UNR_20to64  FUNR_20to64  MUNR_20to64  FLFPR_20to64_Under6  TotalPop  Households  H_Under6_BothWork  H_Under6_FWork  H_Under6_MWork  H_Under6_SingleM  MCInfant  MCInfant_flag  MCToddler  MCToddler_flag  MCPreschool  MCPreschool_flag  _75CInfant  _75CInfant_flag  _75CToddler  _75CToddler_flag  _75CPreschool  _75CPreschool_flag
3529    Florida       Alachua County             12001       2018         5.7          4.9          6.5                 69.1    263148       97048               7023            3659             462            4078.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3540    Florida         Baker County             12003       2018         5.5          4.8          6.1                 77.4     27785        8625               1066             242               2             284.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3551    Florida           Bay County             12005       2018         5.8          5.5          6.1                 71.4    182482       70199               4513            2895             200            4039.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3562    Florida      Bradford County             12007       2018         5.4          6.7          4.1                 64.6     26979        8993                463             227             104             783.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3573    Florida       Brevard County             12009       2018         6.0          5.1          6.8                 65.4    576808      228888              10496            7905             789            9182.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3584    Florida       Broward County             12011       2018         6.2          6.5          5.8                 76.2   1909151      682088              48459           23735            1816           41616.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3595    Florida       Calhoun County             12013       2018         5.8          6.7          5.1                 77.7     14444        4556                347             118              15             192.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3606    Florida     Charlotte County             12015       2018         7.1          7.3          7.0                 70.8    176954       76150               1864            1444             178            1911.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3617    Florida        Citrus County             12017       2018         8.1          6.6          9.4                 67.6    143087       62762               1554            1434             140            1842.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3628    Florida          Clay County             12019       2018         6.9          8.4          5.6                 69.4    207291       73398               4864            3330             367            3461.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3639    Florida       Collier County             12021       2018         4.3          5.3          3.4                 70.3    363922      140942               5999            4839             221            5284.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3650    Florida      Columbia County             12023       2018         8.5          6.6         10.3                 71.5     69105       24985               1646             822             200            1632.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3661    Florida        DeSoto County             12027       2018         4.8          6.8          3.7                 55.3     36399       11996                427             740              21             797.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3664    Florida         Dixie County             12029       2010        10.9          4.0         15.6                 70.0     16196        4909                586             233               5             220.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3665    Florida         Dixie County             12029       2011        11.0          8.7         12.8                 68.3     16317        5380                443             309               4             140.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3666    Florida         Dixie County             12029       2012         8.4          6.9          9.7                 67.3     16301        6014                419             321               4             327.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3667    Florida         Dixie County             12029       2013         8.2          8.3          8.2                 64.1     16234        6130                357             158               5             105.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3668    Florida         Dixie County             12029       2014         7.9          9.7          6.4                 57.4     16137        6020                261             149               4             132.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3672    Florida         Dixie County             12029       2018         4.8          6.2          3.6                 78.3     16437        6520                138             111              34             293.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3683    Florida         Duval County             12031       2018         6.2          6.3          6.1                 71.2    924229      354387              24169           14379            1548           24990.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3694    Florida      Escambia County             12033       2018         6.1          6.6          5.7                 62.7    311522      118740               6409            4933             636            7079.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3705    Florida       Flagler County             12035       2018         4.8          4.4          5.1                 69.7    107139       40629               1832             715              88            1275.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3716    Florida      Franklin County             12037       2018         6.6          5.1          7.8                 63.0     11736        4297                190              80              16             146.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3727    Florida       Gadsden County             12039       2018         7.3          6.9          7.6                 75.6     46017       17080                831             263               0            1688.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3738    Florida     Gilchrist County             12041       2018         5.0          5.2          4.9                 72.8     17615        6511                284             240              71             336.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3749    Florida        Glades County             12043       2018        11.3         11.3         11.2                 76.8     13363        4433                155             108               0             174.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3760    Florida          Gulf County             12045       2018         7.6          9.1          6.5                 61.4     16055        5359                286             265               0             225.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3769    Florida      Hamilton County             12047       2016        13.6         10.8         16.4                 56.5     14362        4717                 48             158              23             501.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3770    Florida      Hamilton County             12047       2017        12.1          9.0         15.4                 56.1     14238        4551                 98             170              26             407.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3771    Florida      Hamilton County             12047       2018        13.6          9.9         17.2                 56.6     14269        4485                 89             296              39             374.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3782    Florida        Hardee County             12049       2018         5.8          5.1          6.2                 58.5     27228        7772                552             482              16             662.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3793    Florida        Hendry County             12051       2018         7.2          9.7          5.4                 51.6     40127       12027                457             722              14            1538.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3804    Florida      Hernando County             12053       2018         7.1          6.7          7.4                 76.9    182696       73541               3259            1819             162            3009.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3815    Florida     Highlands County             12055       2018        10.3          9.0         11.5                 67.0    102101       41026               1980            1149              82            1271.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3826    Florida  Hillsborough County             12057       2018         5.7          6.0          5.4                 70.5   1378883      516478              33049           21757            1995           32427.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3837    Florida        Holmes County             12059       2018        10.2         12.4          8.4                 76.6     19430        7016                381             156              13             263.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3848    Florida  Indian River County             12061       2018         7.1          7.8          6.5                 79.4    150984       57403               3037            1505             166            1857.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3859    Florida       Jackson County             12063       2018         7.8          6.5          9.1                 78.4     48472       16894                913             292              88            1006.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3870    Florida     Jefferson County             12065       2018         5.1          4.7          5.6                 82.6     14105        5771                203             256               0             213.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3881    Florida     Lafayette County             12067       2018        12.0          7.8         14.5                 33.2      8744        2095                289              46               0             331.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3892    Florida          Lake County             12069       2018         6.1          6.3          5.9                 75.6    335362      130190               7300            4207             563            5616.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3903    Florida           Lee County             12071       2018         5.7          6.3          5.2                 70.5    718679      271861              13028            8449            1025           12048.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3914    Florida          Leon County             12073       2018         6.5          5.9          7.1                 76.2    288102      112918               6833            3111             468            5393.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3925    Florida          Levy County             12075       2018         6.3          6.7          5.8                 61.7     39961       16433                794             388              30             682.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3936    Florida       Liberty County             12077       2018        10.2          1.5         16.2                 82.2      8365        2381                149              28               0             159.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3947    Florida       Madison County             12079       2018         5.2          4.8          5.6                 74.3     18474        6682                273             167               4             503.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3958    Florida       Manatee County             12081       2018         5.5          5.4          5.6                 72.8    373853      143652               6723            4752             598            6704.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3969    Florida        Marion County             12083       2018         8.6          7.7          9.5                 70.6    348371      136514               6109            4303             649            7236.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN
3980    Florida        Martin County             12085       2018         4.9          4.8          5.0                 64.8    157581       63865               2546            2110             234            1634.0       NaN            NaN        NaN             NaN          NaN               NaN         NaN              NaN          NaN               NaN            NaN                 NaN

### Observation: 
The 76 rows with 12 columns of NaN values are spread out throughout different counties in Florida. Therefore, not just one county's data will be affected if these rows are dropped.

In [13]:
#drop rows with any NaN values, in place
florida_df.dropna(inplace=True)

#display the modified DataFrame
florida_df

     State_Name          County_Name  County_FIPS_Code  StudyYear  UNR_20to64  FUNR_20to64  MUNR_20to64  FLFPR_20to64_Under6  TotalPop  Households  H_Under6_BothWork  H_Under6_FWork  H_Under6_MWork  H_Under6_SingleM  MCInfant  MCInfant_flag  MCToddler  MCToddler_flag  MCPreschool  MCPreschool_flag  _75CInfant  _75CInfant_flag  _75CToddler  _75CToddler_flag  _75CPreschool  _75CPreschool_flag
3519    Florida       Alachua County             12001       2008        4.10         4.70         3.60                67.10    239046       96894               5618            3675             498            4499.0    137.65            3.0     115.54             1.0       106.36               3.0      165.00              3.0       138.50               1.0         127.50                 3.0
3520    Florida       Alachua County             12001       2009        5.80         5.60         6.00                67.70    238990       96518               5236            4026             398            4258.0    145.99            3.0     126.80             1.0       116.79               3.0      175.00              3.0       152.00               1.0         140.00                 3.0
3521    Florida       Alachua County             12001       2010        5.80         6.10         5.60                67.30    244247       97540               5128            3696             431            4298.0    149.55            3.0     129.75             1.0       119.46               3.0      179.81              3.0       154.83               1.0         142.96                 3.0
3522    Florida       Alachua County             12001       2011        6.70         6.80         6.60                70.70    246203       97542               5467            3364             414            4376.0    153.10            3.0     132.69             1.0       122.12               3.0      184.61              3.0       157.67               1.0         145.93                 3.0
3523    Florida       Alachua County             12001       2012        7.30         6.90         7.60                70.00    247973       96544               5758            3416             392            4426.0    156.66            3.0     135.64             1.0       124.79               3.0      189.42              3.0       160.50               1.0         148.89                 3.0
3524    Florida       Alachua County             12001       2013        8.10         7.50         8.60                68.60    249848       96043               5496            3799             372            4632.0    160.22            1.0     138.58             1.0       127.45               1.0      194.22              1.0       163.33               1.0         151.85                 1.0
3525    Florida       Alachua County             12001       2014        8.10         7.70         8.60                69.70    251759       96137               5808            3705             365            4969.0    159.70            1.0     139.78             1.0       124.58               1.0      201.95              1.0       169.67               1.0         156.19                 1.0
3526    Florida       Alachua County             12001       2015        7.40         6.80         8.00                74.00    254218       96703               6176            3656             503            4568.0    159.18            1.0     140.97             1.0       121.71               1.0      209.68              1.0       176.01               1.0         160.53                 1.0
3527    Florida       Alachua County             12001       2016        6.50         5.70         7.30                74.00    256581       96336               6155            3718             555            4423.0    158.66            1.0     142.17             1.0       118.84               1.0      217.41              1.0       182.35               1.0         164.87                 1.0
3528    Florida       Alachua County             12001       2017        6.20         5.60         6.70                70.20    259865       97485               6417            3802             531            4285.0    158.14            1.0     143.36             1.0       115.97               1.0      225.14              1.0       188.69               1.0         169.21                 1.0
3530    Florida         Baker County             12003       2008        6.17         3.43         8.44                71.98     25628        7672                823             277             128             658.0     93.85            3.0      89.68             1.0        83.42               3.0      112.50              3.0       107.50               1.0         100.00                 3.0
3531    Florida         Baker County             12003       2009        7.30         4.00        10.10                70.40     25478        7680                591             443             124             724.0    104.28            3.0      87.59             1.0        79.25               3.0      125.00              3.0       105.00               1.0          95.00                 3.0
3532    Florida         Baker County             12003       2010        6.20         4.10         8.20                74.70     26548        8309                719             393             129             811.0    109.51            3.0      92.57             1.0        83.40               3.0      126.51              3.0       106.88               1.0          95.73                 3.0
3533    Florida         Baker County             12003       2011       10.10         6.50        13.30                68.10     26863        8333                846             506              19             720.0    114.74            3.0      97.55             1.0        87.54               3.0      128.01              3.0       108.75               1.0          96.46                 3.0
3534    Florida         Baker County             12003       2012        9.70         6.30        12.60                67.50     27010        8424                851             550              14             707.0    119.97            3.0     102.52             1.0        91.69               3.0      129.52              3.0       110.63               1.0          97.19                 3.0
3535    Florida         Baker County             12003       2013       10.10         6.70        13.20                62.60     27069        8216                883             552              17             674.0    125.21            1.0     107.50             1.0        95.83               1.0      131.03              1.0       112.50               1.0          97.92                 1.0
3536    Florida         Baker County             12003       2014        9.10         7.40        10.70                67.20     27057        8351                883             432               6             684.0    127.60            1.0     111.25             1.0        97.92               1.0      133.01              1.0       115.00               1.0          98.96                 1.0
3537    Florida         Baker County             12003       2015        8.10         6.30         9.60                65.80     27135        8205                851             469               1             532.0    130.00            1.0     115.00             1.0       100.00               1.0      135.00              1.0       117.50               1.0         100.00                 1.0
3538    Florida         Baker County             12003       2016        6.60         5.10         8.10                73.70     27312        8270                994             376               2             547.0    132.40            1.0     118.75             1.0       102.09               1.0      136.99              1.0       120.00               1.0         102.09                 1.0
3539    Florida         Baker County             12003       2017        5.80         4.20         7.30                70.60     27537        8299               1019             307               2             374.0    134.79            1.0     122.50             1.0       104.17               1.0      138.97              1.0       125.16               1.0         104.17                 1.0
3541    Florida           Bay County             12005       2008        4.90         5.70         4.20                64.00    163805       71603               3977            3677             144            3641.0    124.33            3.0      99.46             1.0        93.14               3.0      147.50              3.0       118.00               1.0         110.50                 3.0
3542    Florida           Bay County             12005       2009        5.70         6.30         5.10                69.10    163451       68632               3993            3272             323            3834.0    126.43            3.0     101.99             1.0        93.56               3.0      150.00              3.0       121.00               1.0         111.00                 3.0
3543    Florida           Bay County             12005       2010        6.80         6.80         6.80                66.60    166798       68807               3828            3012             352            3434.0    131.78            3.0     108.62             1.0        97.56               3.0      151.14              3.0       124.50               1.0         112.35                 3.0
3544    Florida           Bay County             12005       2011        7.50         7.00         8.00                69.40    167645       68819               4701            2999             330            3101.0    137.13            3.0     115.24             1.0       101.56               3.0      152.28              3.0       128.00               1.0         113.70                 3.0
3545    Florida           Bay County             12005       2012        8.80         8.20         9.40                71.60    168957       68862               4840            2782             293            3196.0    142.47            3.0     121.87             1.0       105.55               3.0      153.41              3.0       131.49               1.0         115.04                 3.0
3546    Florida           Bay County             12005       2013        9.30         8.40        10.10                71.00    170704       67561               4516            2721             536            3247.0    147.82            1.0     128.50             1.0       109.55               1.0      154.55              1.0       134.99               1.0         116.39                 1.0
3547    Florida           Bay County             12005       2014        9.30         8.00        10.40                69.80    172988       67388               4298            2559             386            3504.0    148.91            1.0     130.76             1.0       110.95               1.0      157.28              1.0       136.40               1.0         120.15                 1.0
3548    Florida           Bay County             12005       2015        8.00         7.20         8.80                74.20    175353       67922               4364            2067             430            3895.0    150.00            1.0     133.01             1.0       112.35               1.0      160.00              1.0       137.81               1.0         123.91                 1.0
3549    Florida           Bay County             12005       2016        6.90         6.40         7.40                72.00    178361       67939               3867            2597             467            4167.0    151.09            1.0     135.27             1.0       113.75               1.0      162.73              1.0       139.22               1.0         127.67                 1.0
3550    Florida           Bay County             12005       2017        6.10         5.30         6.90                71.20    180117       68667               3919            2688             503            4062.0    152.18            1.0     137.52             1.0       115.15               1.0      165.45              1.0       140.63               1.0         131.43                 1.0
3552    Florida      Bradford County             12007       2008        4.30         5.70         3.50                63.30     28730        8493                698             254              12             463.0    118.48            3.0      77.55             1.0        75.40               3.0      137.50              3.0        90.00               1.0          87.50                 3.0
3553    Florida      Bradford County             12007       2009        8.10        10.20         6.40                72.10     28841        8484                779             309               5             661.0    112.02            3.0      77.55             1.0        77.55               3.0      130.00              3.0        90.00               1.0          90.00                 3.0
3554    Florida      Bradford County             12007       2010        9.70         9.90         9.50                69.20     28750        8931                758             260              65             799.0    111.31            3.0      81.60             1.0        77.33               3.0      126.25              3.0        92.19               1.0          89.38                 3.0
3555    Florida      Bradford County             12007       2011       13.00        12.80        13.20                70.50     28701        9188                692             363              68             662.0    110.61            3.0      85.65             1.0        77.12               3.0      122.51              3.0        94.38               1.0          88.75                 3.0
3556    Florida      Bradford County             12007       2012       14.60        13.50        15.50                67.20     28404        9065                661             383              55             685.0    109.90            3.0      89.70             1.0        76.90               3.0      118.76              3.0        96.56               1.0          88.13                 3.0
3557    Florida      Bradford County             12007       2013       15.10        14.10        16.00                72.60     27981        8857                641             427             100             718.0    109.19            1.0      93.75             1.0        76.68               1.0      115.02              1.0        98.75               1.0          87.50                 1.0
3558    Florida      Bradford County             12007       2014       14.40        13.40        15.30                67.70     27552        8824                428             393              82             684.0    112.37            1.0      96.88             1.0        84.59               1.0      118.17              1.0       101.88               1.0          93.13                 1.0
3559    Florida      Bradford County             12007       2015       12.10        12.00        12.20                74.20     27223        8770                534             265              32             690.0    115.54            1.0     100.00             1.0        92.50               1.0      121.32              1.0       105.00               1.0          98.75                 1.0
3560    Florida      Bradford County             12007       2016       10.40         9.90        10.90                72.60     26919        8704                496             209              34             805.0    118.72            1.0     103.13             1.0       100.41               1.0      124.48              1.0       108.13               1.0         104.38                 1.0
3561    Florida      Bradford County             12007       2017        7.20         8.70         5.70                68.70     26775        8980                508             194             115             777.0    121.90            1.0     106.25             1.0       108.32               1.0      127.63              1.0       111.25               1.0         115.64                 1.0
3563    Florida       Brevard County             12009       2008        5.50         5.50         5.50                63.00    534165      217481              12104            8788             340            7719.0    138.23            3.0     115.48             1.0       110.00               3.0      164.00              3.0       137.00               1.0         130.50                 3.0
3564    Florida       Brevard County             12009       2009        6.40         6.60         6.10                63.30    532697      218885              11268            9639             537            7396.0    147.51            3.0     122.22             1.0       114.63               3.0      175.00              3.0       145.00               1.0         136.00                 3.0
3565    Florida       Brevard County             12009       2010        8.00         8.20         7.90                65.20    540583      220871              11599            8901             663            7384.0    151.86            3.0     126.19             1.0       115.28               3.0      175.83              3.0       148.02               1.0         135.79                 3.0
3566    Florida       Brevard County             12009       2011        9.90         9.90         9.90                65.40    542320      219669              11055            8861             621            7698.0    156.22            3.0     130.15             1.0       115.93               3.0      176.65              3.0       151.05               1.0         135.59                 3.0
3567    Florida       Brevard County             12009       2012       11.00        10.90        11.10                68.30    544019      220414              11595            7616             694            8463.0    160.58            3.0     134.12             1.0       116.57               3.0      177.48              3.0       154.07               1.0         135.38                 3.0
3568    Florida       Brevard County             12009       2013       11.60        11.30        11.90                67.80    545667      220277              11137            7001             819            9168.0    164.94            1.0     138.09             1.0       117.22               1.0      178.30              1.0       157.09               1.0         135.17                 1.0
3569    Florida       Brevard County             12009       2014       11.50        10.90        11.90                67.50    548891      221582              10955            6814             856            9202.0    166.39            1.0     140.60             1.0       121.93               1.0      180.42              1.0       158.75               1.0         139.34                 1.0
3570    Florida       Brevard County             12009       2015       10.30         9.50        11.10                70.10    553591      222791              10299            6643             814            9419.0    167.84            1.0     143.10             1.0       126.63               1.0      182.53              1.0       160.40               1.0         143.51                 1.0
3571    Florida       Brevard County             12009       2016        8.60         7.50         9.70                69.00    560683      224373              10655            6544             923            9688.0    169.29            1.0     145.61             1.0       131.34               1.0      184.65              1.0       162.06               1.0         147.68                 1.0

In [14]:
#displaying summary statistics for the DataFrame
florida_df.describe()

       County_FIPS_Code    StudyYear  UNR_20to64  FUNR_20to64  MUNR_20to64  FLFPR_20to64_Under6      TotalPop     Households  H_Under6_BothWork  H_Under6_FWork  H_Under6_MWork  H_Under6_SingleM    MCInfant  MCInfant_flag   MCToddler  MCToddler_flag  MCPreschool  MCPreschool_flag  _75CInfant  _75CInfant_flag  _75CToddler  _75CToddler_flag  _75CPreschool  _75CPreschool_flag
count        661.000000   661.000000  661.000000   661.000000   661.000000           661.000000  6.610000e+02     661.000000         661.000000      661.000000      661.000000        661.000000  661.000000     661.000000  661.000000           661.0   661.000000        661.000000  661.000000       661.000000   661.000000             661.0     661.000000          661.000000
mean       12068.095310  2012.479576    9.261694     9.107156     9.414796            67.652027  2.884467e+05  109128.904690        6769.856278     4172.931921      369.027231       5799.098336  144.258442       1.928896  122.442995             1.0   110.568926          1.623298  161.526672         1.928896   138.105401               1.0     125.754539            1.623298
std           38.390912     2.873857    2.679307     2.907415     3.173691             7.748009  4.536514e+05  163870.097259       11538.636353     6625.078746      591.907463      10016.519045   26.369410       0.998224   21.963202             0.0    18.652365          0.927036   30.015592         0.998224    25.286994               0.0      22.756946            0.927036
min        12001.000000  2008.000000    2.450000     1.460000     1.340000            33.100000  7.723000e+03    1884.000000          86.000000        4.000000        0.000000         60.000000   77.550000       1.000000   64.630000             1.0    64.630000          1.000000   90.000000         1.000000    75.000000               1.0      75.000000            1.000000
25%        12037.000000  2010.000000    7.300000     7.100000     7.100000            64.100000  2.853700e+04    8824.000000         604.000000      376.000000       25.000000        672.000000  125.550000       1.000000  108.000000             1.0    97.340000          1.000000  139.690000         1.000000   120.000000               1.0     107.560000            1.000000
50%        12069.000000  2012.000000    9.100000     8.800000     9.100000            68.500000  1.167540e+05   50928.000000        1873.000000     1343.000000      139.000000       1832.000000  142.500000       1.000000  121.720000             1.0   110.160000          1.000000  156.860000         1.000000   137.000000               1.0     125.000000            1.000000
75%        12101.000000  2015.000000   10.900000    10.800000    11.200000            72.100000  3.188860e+05  122972.000000        6909.000000     4537.000000      397.000000       6199.000000  160.490000       3.000000  137.210000             1.0   123.050000          3.000000  179.830000         3.000000   154.070000               1.0     140.550000            3.000000
max        12133.000000  2017.000000   18.600000    20.200000    21.000000            95.800000  2.702602e+06  858289.000000       68611.000000    40837.000000     3915.000000      61036.000000  228.650000       3.000000  196.190000             1.0   160.560000          3.000000  273.670000         3.000000   214.030000               1.0     191.210000            3.000000

In [15]:
#getting data type info for the dataframe
florida_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 661 entries, 3519 to 4254
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   State_Name           661 non-null    object
 1   County_Name          661 non-null    object
 2   County_FIPS_Code     661 non-null    int64
 3   StudyYear            661 non-null    int64
 4   UNR_20to64           661 non-null    float64
 5   FUNR_20to64          661 non-null    float64
 6   MUNR_20to64          661 non-null    float64
 7   FLFPR_20to64_Under6  661 non-null    float64
 8   TotalPop             661 non-null    int64
 9   Households           661 non-null    int64
 10  H_Under6_BothWork    661 non-null    int64
 11  H_Under6_FWork       661 non-null    int64
 12  H_Under6_MWork       661 non-null    int64
 13  H_Under6_SingleM     661 non-null    float64
 14  MCInfant             661 non-null    float64
 15  MCInfant_flag        661 non-null    float64
 16  MCToddler            661 non-null    float64
 17  MCToddler_flag       661 non-null    float64
 18  MCPreschool          661 non-null    float64
 19  MCPreschool_flag     661 non-null    float64
 20  _75CInfant           661 non-null    float64
 21  _75CInfant_flag      661 non-null    float64
 22  _75CToddler          661 non-null    float64
 23  _75CToddler_flag     661 non-null    float64
 24  _75CPreschool        661 non-null    float64
 25  _75CPreschool_flag   661 non-null    float64
dtypes: float64(17), int64(7), object(2)
memory usage: 139.4+ KB

In [16]:
#UN-COMMENT WHEN READY TO SAVE TO FILE

#saving the filtered data (specific to my story) as an excel file. 
###florida_df.to_excel('florida_data.xlsx', index=False)